---
- name: Install necessary packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - apt-transport-https
    - ca-certificates

- name: Import syncthing gpg key
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /etc/apt/keyrings/syncthing-archive-keyring.gpg

- name: Add stable repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present
  when: not syncthing_candidate 

- name: Add candidate repository
  ansible.builtin.apt_repository:
    repo: echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing candidate"
    state: present
  when: syncthing_candidate

- name: Install syncthing
  ansible.builtin.package:
    name: syncthing
    state: present

- name: create {{ syncthing_user }} user
  ansible.builtin.user:
    name: '{{ syncthing_user }}'
    create_home: yes
    comment: syncthing user managed by Ansible
    password: '!'

- name: Enable syncthing service
  ansible.builtin.systemd_service:
    name: syncthing@{{ syncthing_user }}
    enabled: true
    state: started
