---
- name: Install necessary packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - apt-transport-https
    - ca-certificates

- name: import keyrings
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /etc/apt/keyrings/syncthing-archive-keyring.gpg

- name: add repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present

- name: install syncthing
  ansible.builtin.package:
    name: '{{ syncthing_version }}'
    state: present

- name: create {{ syncthing_user }} user
  ansible.builtin.user:
    name: '{{ syncthing_user }}'
    create_home: yes
    comment: Syncthing user managed by Ansible
    password: '!'

- name: Enable syncthing service
  ansible.builtin.systemd_service:
    name: syncthing@syncthing
    enabled: true
    state: started
